import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "../components/Header/index";
import "primereact/resources/themes/lara-light-indigo/theme.css"; // or another theme
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import "primeflex/primeflex.css";
import Head from 'next/head'
import FloatingChatButton from "@/components/FloatingChatButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" type="image/png" href="/favicon.png" />
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        {children}
        <FloatingChatButton />
      </body>
    </html>
  );
}
